# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_place', models.TextField()),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(default='test@test.com', max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default='test@test.com', on_delete=django.db.models.deletion.CASCADE, to='date.User'),
        ),
        migrations.AddField(
            model_name='date',
            name='user',
            field=models.ForeignKey(default='test@test.com', on_delete=django.db.models.deletion.CASCADE, to='date.User'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default='test@test.com', on_delete=django.db.models.deletion.CASCADE, to='date.User'),
        ),
    ]
