# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
