# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0003_auto_20171116_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='interested_users',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
