# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0004_date_interested_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='create_date',
            new_name='when',
        ),
        migrations.RenameField(
            model_name='date',
            old_name='date_place',
            new_name='where',
        ),
    ]
