# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0005_auto_20171117_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='hot_date_meter',
        ),
        migrations.RemoveField(
            model_name='date',
            name='interested',
        ),
    ]
