# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0006_auto_20171120_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='confirmed_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
