# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0007_date_confirmed_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='accepted',
            new_name='matched',
        ),
        migrations.AddField(
            model_name='date',
            name='imbuyin_value',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
