# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_email', models.EmailField(max_length=254)),
                ('date_place', models.TextField()),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.SmallIntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='date.Date')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='date.Date'),
        ),
    ]
