# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0002_auto_20160925_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, primary_key=True, serialize=False),
        ),
    ]
